import styles from './aboutthissite.module.css';
import { TextGenerateEffect } from "@/components/ui/text-generate-effect";

const AboutThisSite = () => {
    return (
        <div className={styles.container}>
            <h1 className={styles.title}>About This Site</h1>

            <section className={styles.section}>
                <h2 className={styles.sectionTitle}><strong>Frontend</strong></h2>
                <TextGenerateEffect words='This website is built using Next.js. It is ideal for a portfolio site due to its performance and SEO benefits.' />
            </section>

            <section className={styles.section}>
                <h2 className={styles.sectionTitle}><strong>Backend</strong></h2>
                <TextGenerateEffect words='The backend is written by Python. The &quot;Chat With My AI&quot; feature uses LangChain for managing conversations and integrations. The LLM I choose is GPT-4o-mini, a model optimized for cost-efficient and accurate large language model interactions.' /><br />
                <TextGenerateEffect words='My personal information is vectorized and stored in Pinecone for real-time retrieval. I use RAG to fetch relevant data from Pinecone, enhancing responses generated by GPT-4o-mini for accurate and relevant AI interactions.' /><br />
                <TextGenerateEffect words='The backend is packaged as a Docker image and deployed via AWS Lambda. The API is exposed through Lambda&apos;s Function URL, ensuring efficient scaling and cost optimization while maintaining simplicity in the architecture.' />
            </section>

            <section className={styles.section}>
                <h2 className={styles.sectionTitle}><strong>Deployment</strong></h2>
                <TextGenerateEffect words='The frontend is automatically deployed via AWS Amplify using its built-in CI/CD features.' /><br />
                <TextGenerateEffect words='The backend CI/CD is managed with AWS CodePipeline, written using AWS CDK Python, and includes resources like Lambda, Docker Image, and Function URL for automated deployment.' />
            </section>

            <section className={styles.section}>
                <h2 className={styles.sectionTitle}><strong>Trade-offs and Considerations</strong></h2>
                <TextGenerateEffect words='Although running Docker images inside AWS Lambda increases the cold start time, this architecture was chosen to maintain a consistent environment. The decision to skip API Gateway helps reduce the complexity and costs for this lightweight API. Additionally, the use of RAG improves AI interactions by ensuring that only the most relevant and personalized information is retrieved from Pinecone, thus balancing the trade-offs between cost and performance.' />
            </section>
        </div>
    );
};

export default AboutThisSite;
